name: ai_resume
description: "RAG based Resume analyzer app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

publish_to: none
version: 1.0.0+250807

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # State management
  bloc: 8.1.4
  flutter_bloc: ^8.1.6

  # Functional programming
  fpdart: 1.1.1

  # Dependency injection
  get_it: ^8.2.0
  injectable: ^2.5.1

  # Data models
  freezed_annotation: 2.4.4
  json_annotation: ^4.9.0
  equatable: 2.0.7
  google_fonts: ^6.3.1
  flutter_native_splash: ^2.4.6
  simple_form_field:
    git:
      url: https://github.com/basnetjiten/simple_form_field.git
  cupertino_icons: 1.0.8


  # UI and animations
  loading_animation_widget: ^1.3.0

  # Session and Storage
  hive_local_storage: 2.0.0-dev.4

  internet_connection_checker_plus: ^2.7.2

  animated_text_kit: ^4.2.3




  # Routing
  auto_route: ^9.2.2

  # Network
  dio: ^5.9.0
  #gql_dio_link: ^1.0.2
  pretty_dio_logger: ^1.4.0

  # Files upload and download

  dio_filex_uploader:
    git:
      url: https://github.com/basnetjiten/dio-filex-uploader

  # Permission handler
  permission_handler: ^12.0.1

  # Utils
  open_file_manager: ^2.0.1
  file_picker: ^10.3.2
  uuid: 4.5.1
  intl: 0.20.2
  logger: ^2.6.1
  collection: 1.19.1


  flutter_launcher_icons: ^0.14.4
  envied: ^1.0.1

dev_dependencies:
  flutter_lints: 6.0.0
  build_runner: ^2.4.12
  freezed: 2.5.2
  json_serializable: 6.8.0
  injectable_generator: 2.6.2
  auto_route_generator: 9.0.0
  flutter_gen_runner: 5.4.0
  envied_generator: ^1.0.1

dependency_overrides:
  freezed_annotation: 2.4.4

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/localization/arb
  output_dir: lib/localization/generated

# Flutter asset generator
flutter_gen:
  output: lib/gen
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/icons/